CREATE TABLE IF NOT EXISTS categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS products (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255)   NOT NULL,
    description TEXT,
    price       DECIMAL(10, 2) NOT NULL,
    category_id BIGINT         NOT NULL,
    image_url   VARCHAR(255),
    active      BOOLEAN,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);