CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id        BIGINT NOT NULL,
    quantity          INT    NOT NULL,
    reserved_quantity INT    DEFAULT 0,
    version           BIGINT NOT NULL
);